T = {
    "ru": {
        "menu_title": "⏰ <b>Time Manager</b>",
        "menu_desc": "Управляй своим временем легко!",
        "menu_add": "➕ <b>Добавить</b> — занять интервал",
        "menu_delete": "❌ <b>Удалить</b> — убрать интервал",
        "menu_busy": "📋 <b>Моя занятость</b> — всё расписание",
        "menu_notif": "⏰ <b>Напоминания</b> — время уведомлений",
        "menu_help": "📖 <b>Справка</b> — /help",
        "select_day": "Выбери день:",
        "start_hour": "⏰ Час начала:",
        "start_minute": "⏱ Минуты начала:",
        "end_hour": "⏰ Час окончания:",
        "end_minute": "⏱ Минуты окончания:",
        "added": "✅ Добавлено: {day} {start}-{end}\n\nВыбери день для нового интервала:",
        "done": "Готово",
        "no_busy": "Нет занятости",
        "delete_title": "Удалить:",
        "deleted": "Удалено",
        "busy_title": "📅 <b>Твоя занятость:</b>",
        "no_busy_list": "У тебя нет занятости",
        "notif_current": "Текущее время: {time}\n⏰ Час напоминания:",
        "notif_hour": "⏱ Минуты напоминания:",
        "notif_set": "✅ Время напоминаний установлено на {time}",
        "conflict_time": "Начало должно быть раньше окончания!",
        "conflict_slot": "⚠️ Это время пересекается с другой занятостью!",
        "help_title": "📖 <b>Справка по боту</b>",
        "help_add": "➕ <b>Добавить</b> — добавь занятость:\n  1. Выбери день недели\n  2. Укажи час и минуту начала\n  3. Укажи час и минуту окончания",
        "help_del": "❌ <b>Удалить</b> — удали занятость кнопкой",
        "help_busy": "📋 <b>Моя занятость</b> — посмотреть всё расписание",
        "help_notif": "⏰ <b>Напоминания</b> — настроить время уведомлений",
        "help_info": "🔔 Уведомления приходят каждый день в выбранное время\nБот покажет свободные окна и предложит идеи",
        "help_start": "/start — главное меню",
        "help_help": "/help — эта справка",
        "lang_title": "🌐 Выбери язык / Choose language:",
        "lang_set_ru": "✅ Язык изменён на русский",
        "lang_set_en": "✅ Language changed to English",
        "back": "⬅️ Назад",
        "free_time": "📅 Свободное время:",
        "no_suggestions": "Нет предложений",
        "tz_title": "🌍 Выбери часовой пояс:",
        "tz_current": "Текущий: {tz}",
        "tz_set": "✅ Часовой пояс установлен: {tz}",
        "tz_btn": "🌍 Часовой пояс",
    },
    "en": {
        "menu_title": "⏰ <b>Time Manager</b>",
        "menu_desc": "Manage your time easily!",
        "menu_add": "➕ <b>Add</b> — busy slot",
        "menu_delete": "❌ <b>Delete</b> — remove slot",
        "menu_busy": "📋 <b>My Schedule</b> — full timetable",
        "menu_notif": "⏰ <b>Notifications</b> — notification time",
        "menu_help": "📖 <b>Help</b> — /help",
        "select_day": "Select a day:",
        "start_hour": "⏰ Start hour:",
        "start_minute": "⏱ Start minute:",
        "end_hour": "⏰ End hour:",
        "end_minute": "⏱ End minute:",
        "added": "✅ Added: {day} {start}-{end}\n\nSelect a day for another slot:",
        "done": "Done",
        "no_busy": "No busy slots",
        "delete_title": "Delete:",
        "deleted": "Deleted",
        "busy_title": "📅 <b>Your Schedule:</b>",
        "no_busy_list": "You have no busy slots",
        "notif_current": "Current time: {time}\n⏰ Notification hour:",
        "notif_hour": "⏱ Notification minute:",
        "notif_set": "✅ Notification time set to {time}",
        "conflict_time": "Start must be before end!",
        "conflict_slot": "⚠️ This time overlaps with another slot!",
        "help_title": "📖 <b>Bot Help</b>",
        "help_add": "➕ <b>Add</b> — add busy slot:\n  1. Select a day of week\n  2. Set start hour and minute\n  3. Set end hour and minute",
        "help_del": "❌ <b>Delete</b> — remove a slot with button",
        "help_busy": "📋 <b>My Schedule</b> — view full timetable",
        "help_notif": "⏰ <b>Notifications</b> — set notification time",
        "help_info": "🔔 Notifications arrive daily at your chosen time\nBot shows free windows and suggests ideas",
        "help_start": "/start — main menu",
        "help_help": "/help — this help",
        "lang_title": "🌐 Choose language / Выбери язык:",
        "lang_set_ru": "✅ Язык изменён на русский",
        "lang_set_en": "✅ Language changed to English",
        "back": "⬅️ Back",
        "free_time": "📅 Free time:",
        "no_suggestions": "No suggestions",
        "tz_title": "🌍 Choose timezone:",
        "tz_current": "Current: {tz}",
        "tz_set": "✅ Timezone set to: {tz}",
        "tz_btn": "🌍 Timezone",
    }
}

def get(user_lang, key):
    return T.get(user_lang, T["ru"]).get(key, T["ru"].get(key, key))
